// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'backgroundBlue': string;
  'backgroundGray': string;
  'main': string;
  'p': string;
  'section': string;
}
export const cssExports: CssExports;
export default cssExports;
