// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'customZoomcontrol': string;
  'infoContent': string;
  'infoTitle': string;
  'map_wrap': string;
  'radius_border': string;
}
export const cssExports: CssExports;
export default cssExports;
