// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'contact__btn': string;
  'contact__call': string;
  'contact__description': string;
  'contact__email': string;
  'contact__img': string;
  'introudct__description': string;
  'introudct__title': string;
  'land': string;
  'land__contact': string;
  'land__introduce': string;
  'landing__title': string;
  'main__img': string;
  'main__serviceList': string;
  'section': string;
}
export const cssExports: CssExports;
export default cssExports;
