// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'card__icon': string;
  'selected': string;
  'service': string;
  'service__card': string;
  'service__list': string;
}
export const cssExports: CssExports;
export default cssExports;
