// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'imgWrapper': string;
  'profile': string;
}
export const cssExports: CssExports;
export default cssExports;
