// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  btnOpen: string;
  header: string;
  logo: string;
  menuToggle: string;
  navOpen: string;
}
export const cssExports: CssExports;
export default cssExports;
