// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'open': string;
  'question': string;
  'question__card': string;
  'question__card__title': string;
  'question__contact': string;
  'question__content': string;
  'question__list': string;
}
export const cssExports: CssExports;
export default cssExports;
