// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'title__icon': string;
  'typeB': string;
  'typeBDescription': string;
  'typeBList': string;
  'typeBList__card': string;
  'typeBList__img': string;
  'typeB__description': string;
}
export const cssExports: CssExports;
export default cssExports;
