// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'title__icon': string;
  'typeMain': string;
  'typeMainList': string;
  'typeMainList__item': string;
}
export const cssExports: CssExports;
export default cssExports;
