// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'title__icon': string;
  'typeA': string;
  'typeADescription': string;
  'typeAList': string;
  'typeAList__card': string;
  'typeAList__img': string;
}
export const cssExports: CssExports;
export default cssExports;
